// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmA9ZnXcbhH0zY1qIjaL1HnoLL64JyrrA',
    appId: '1:686836839340:web:25e898428e0ab26162c009',
    messagingSenderId: '686836839340',
    projectId: 'driveguide-993ad',
    authDomain: 'driveguide-993ad.firebaseapp.com',
    storageBucket: 'driveguide-993ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_T92lOU1cmC3VOLU7opTlvdJdBl_SOu4',
    appId: '1:686836839340:android:580a839faf1b37fc62c009',
    messagingSenderId: '686836839340',
    projectId: 'driveguide-993ad',
    storageBucket: 'driveguide-993ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBJYguUFGGhs_yERqy13oCqebSJOIxFjY',
    appId: '1:686836839340:ios:5c61fe2cbb8ed22562c009',
    messagingSenderId: '686836839340',
    projectId: 'driveguide-993ad',
    storageBucket: 'driveguide-993ad.appspot.com',
    iosBundleId: 'com.example.driveGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBJYguUFGGhs_yERqy13oCqebSJOIxFjY',
    appId: '1:686836839340:ios:651dca3ca4f895a562c009',
    messagingSenderId: '686836839340',
    projectId: 'driveguide-993ad',
    storageBucket: 'driveguide-993ad.appspot.com',
    iosBundleId: 'com.example.driveGuide.RunnerTests',
  );
}
